[tool.black]
line-length = 100

[tool.vulture]
ignore_names = ["command_*"]
exclude = ["sdk_generation/"]
#ignore_decorators = ["@app.route", "@require_*"]
make_whitelist = true
min_confidence = 60
sort_by_size = true
verbose = false
