info:
  description: P0 Script API
  title: P0 Script API
  version: 1.0.0
openapi: 3.0.2
paths:
  /search_track/:
    get:
      responses:
        '200':
          description: ''
    parameters:
    - in: query
      name: search
      required: true
      schema: {}
    - in: query
      name: toto
      required: false
      schema:
        default: 4242
        nullable: false
        type: integer
  /test/:
    get:
      responses:
        '200':
          description: ''
