# This file is autogenerated. Do not edit.

from sr.enums.ableton_command_enum import AbletonCommandEnum

# noinspection SpellCheckingInspection
speech_recognition_dictionary = {
    AbletonCommandEnum.BASS: [
        "thus",
        "this",
        "bess",
    ],
    AbletonCommandEnum.CLAP: [
        "the up",
        "up",
        "lab",
        "the club",
        "is it",
        "the exit",
        "the app",
        "club",
        "yep",
        "nope",
        "cap",
    ],
    AbletonCommandEnum.HAT: [
        "at",
        "that&#x27;s",
        "hurts",
    ],
    AbletonCommandEnum.KICK: [
        "he",
        "geek",
        "kek",
        "each",
        "week",
        "keke",
        "key",
    ],
    # TrackWorkEnum.MINITAUR: ["the nato", "the needle", "nieto", "mini tour", "the door", "the though", "though", "me nieto", "me though", "many though", "the nieto", "new though", ],
    AbletonCommandEnum.PIANO: [
        "the new piano",
        "the know",
        "you know",
        "the new",
        "piano",
        "the a new",
        "plenty",
        "planet",
        "know",
    ],
    AbletonCommandEnum.RIDE: [
        "they&#x27;d",
        "hi them",
        "right",
        "them",
        "either",
        "it",
        "hi there",
        "i&#x27;d",
        "hi the",
        "hide",
    ],
    AbletonCommandEnum.SNARE: [
        "snap",
        "snow",
        "snail",
        "now",
    ],
}
