# This file is autogenerated. Do not edit.

from sr.dictionary.TrackWordEnum import TrackWorkEnum

# noinspection SpellCheckingInspection
speech_recognition_dictionary = {
    TrackWorkEnum.BASS: ["thus", "this", "bess", ],
    TrackWorkEnum.CLAP: ["the up", "up", "lab", "the club", "is it", "the exit", "the app", "club", "yep", "nope",
                         "cap", ],
    TrackWorkEnum.HAT: ["at", "that&#x27;s", "hurts", ],
    TrackWorkEnum.KICK: ["he", "geek", "kek", "each", "week", "keke", "key", ],
    # TrackWorkEnum.MINITAUR: ["the nato", "the needle", "nieto", "mini tour", "the door", "the though", "though", "me nieto", "me though", "many though", "the nieto", "new though", ],
    TrackWorkEnum.PIANO: ["the new piano", "the know", "you know", "the new", "piano", "the a new", "plenty", "planet",
                          "know", ],
    TrackWorkEnum.RIDE: ["they&#x27;d", "hi them", "right", "them", "either", "it", "hi there", "i&#x27;d", "hi the",
                         "hide", ],
    TrackWorkEnum.SNARE: ["snap", "snow", "snail", "now", ],
}
