# coding: utf-8

"""
    Protocol0 System API

    backend API for the Protocol0 Control Surface Script. Accessible via HTTP or via MIDI. Executes on python system version without Ableton python environment limitations  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import p0_system_api
from p0_system_api.api.default_api import DefaultApi  # noqa: E501
from p0_system_api.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = p0_system_api.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_rev2_editor(self):
        """Test case for activate_rev2_editor

        Activate Rev2 Editor  # noqa: E501
        """
        pass

    def test_arrow_down(self):
        """Test case for arrow_down

        Arrow Down  # noqa: E501
        """
        pass

    def test_arrow_up(self):
        """Test case for arrow_up

        Arrow Up  # noqa: E501
        """
        pass

    def test_bad_request(self):
        """Test case for bad_request

        Bad Request  # noqa: E501
        """
        pass

    def test_click(self):
        """Test case for click

        Click  # noqa: E501
        """
        pass

    def test_double_click(self):
        """Test case for double_click

        Double Click  # noqa: E501
        """
        pass

    def test_focus_window(self):
        """Test case for focus_window

        Focus Window  # noqa: E501
        """
        pass

    def test_health(self):
        """Test case for health

        Health  # noqa: E501
        """
        pass

    def test_hide_plugins(self):
        """Test case for hide_plugins

        Hide Plugins  # noqa: E501
        """
        pass

    def test_index(self):
        """Test case for index

        Index  # noqa: E501
        """
        pass

    def test_pixel_has_color(self):
        """Test case for pixel_has_color

        Pixel Has Color  # noqa: E501
        """
        pass

    def test_reload_ableton(self):
        """Test case for reload_ableton

        Reload Ableton  # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        Search  # noqa: E501
        """
        pass

    def test_show_device_view(self):
        """Test case for show_device_view

        Show Device View  # noqa: E501
        """
        pass

    def test_show_hide_plugins(self):
        """Test case for show_hide_plugins

        Show Hide Plugins  # noqa: E501
        """
        pass

    def test_show_plugins(self):
        """Test case for show_plugins

        Show Plugins  # noqa: E501
        """
        pass

    def test_show_windows(self):
        """Test case for show_windows

        Show Windows  # noqa: E501
        """
        pass

    def test_sync_presets(self):
        """Test case for sync_presets

        Sync Presets  # noqa: E501
        """
        pass

    def test_toggle_ableton_button(self):
        """Test case for toggle_ableton_button

        Toggle Ableton Button  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
