openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /:
    get:
      operationId: listindexs
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - ''
  /400:
    get:
      operationId: listbad_requests
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - '400'
  /search/{search}:
    get:
      operationId: retrievesearch
      description: ''
      parameters:
      - name: search
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - search
  /action:
    get:
      operationId: listactions
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - action
  /show_plugins:
    get:
      operationId: listshow_plugins
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - show-plugins
  /show_hide_plugins:
    get:
      operationId: listshow_hide_plugins
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - show-hide-plugins
  /hide_plugins:
    get:
      operationId: listhide_plugins
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - hide-plugins
  /pixel_has_color:
    get:
      operationId: listpixel_has_colors
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - pixel-has-color
  /arrow_up:
    get:
      operationId: listarrow_ups
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - arrow-up
  /reload_ableton:
    get:
      operationId: listreload_abletons
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - reload-ableton
  /show_windows:
    get:
      operationId: listshow_windows
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - show-windows
